"""adding info column to the modules

Revision ID: 26935145988c
Revises: 317a9fe783e0
Create Date: 2024-12-09 05:48:11.650480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26935145988c'
down_revision: Union[str, None] = '317a9fe783e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module', sa.Column('info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module', 'info')
    # ### end Alembic commands ###
