"""create run table

Revision ID: 2d99500d2b70
Revises: 
Create Date: 2024-08-14 11:15:37.138182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d99500d2b70'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('data', sa.Column('run_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'data', 'run', ['run_id'], ['id'])
    op.drop_column('data', 'run_tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('run_tag', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'data', type_='foreignkey')
    op.drop_column('data', 'run_id')
    op.drop_table('run')
    # ### end Alembic commands ###
