"""adding indexes on run and module for data table

Revision ID: 317a9fe783e0
Revises: e64a7520d9cb
Create Date: 2024-12-08 12:25:13.125355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '317a9fe783e0'
down_revision: Union[str, None] = 'e64a7520d9cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_data_module_id'), 'data', ['module_id'], unique=False)
    op.create_index(op.f('ix_data_run_id'), 'data', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_run_id'), table_name='data')
    op.drop_index(op.f('ix_data_module_id'), table_name='data')
    # ### end Alembic commands ###
