"""dropping module bb data relationship

Revision ID: 489b3d085cd1
Revises: 4a534ee10399
Create Date: 2025-04-24 05:09:32.887373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '489b3d085cd1'
down_revision: Union[str, None] = '4a534ee10399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
