"""adding probe columns to calibration for module

Revision ID: 4f0263597922
Revises: b283fa450931
Create Date: 2024-12-18 06:53:38.522589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f0263597922'
down_revision: Union[str, None] = 'b283fa450931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_calibration', sa.Column('P1_id', sa.Integer(), nullable=True))
    op.add_column('module_calibration', sa.Column('P2_id', sa.Integer(), nullable=True))
    op.add_column('module_calibration', sa.Column('P3_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'module_calibration', 'sensor_calibration', ['P1_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'module_calibration', 'sensor_calibration', ['P3_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'module_calibration', 'sensor_calibration', ['P2_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'module_calibration', type_='foreignkey')
    op.drop_constraint(None, 'module_calibration', type_='foreignkey')
    op.drop_constraint(None, 'module_calibration', type_='foreignkey')
    op.drop_column('module_calibration', 'P3_id')
    op.drop_column('module_calibration', 'P2_id')
    op.drop_column('module_calibration', 'P1_id')
    # ### end Alembic commands ###
