"""dropping column to change to float

Revision ID: 65e8c53e8978
Revises: 489b3d085cd1
Create Date: 2025-04-24 05:23:23.159412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65e8c53e8978'
down_revision: Union[str, None] = '489b3d085cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bb_resistance_path_data', 'raw_voltage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bb_resistance_path_data', sa.Column('raw_voltage', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
