"""removing ohms and volts column and making it a hybrid property instead!

Revision ID: 76c97f65c84e
Revises: 8ebf2388aaef
Create Date: 2024-12-02 08:47:33.117983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76c97f65c84e'
down_revision: Union[str, None] = '8ebf2388aaef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'ohms')
    op.drop_column('data', 'volts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('volts', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('data', sa.Column('ohms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
