"""changing column type to string, mistake making it datetime

Revision ID: a289539f1f10
Revises: 938a283a3615
Create Date: 2024-12-02 10:24:14.080877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a289539f1f10'
down_revision: Union[str, None] = '938a283a3615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sensor_calibration', 'all_raw_adcs',
               existing_type=postgresql.ARRAY(postgresql.TIMESTAMP()),
               type_=postgresql.ARRAY(sa.String(length=50)),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sensor_calibration', 'all_raw_adcs',
               existing_type=postgresql.ARRAY(sa.String(length=50)),
               type_=postgresql.ARRAY(postgresql.TIMESTAMP()),
               existing_nullable=True)
    # ### end Alembic commands ###
