"""adding correct float column to bb data

Revision ID: ae20ffcd51b3
Revises: 65e8c53e8978
Create Date: 2025-04-24 05:24:02.287875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae20ffcd51b3'
down_revision: Union[str, None] = '65e8c53e8978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bb_resistance_path_data', sa.Column('raw_voltage', sa.Float(), nullable=True))
    op.execute("UPDATE bb_resistance_path_data SET raw_voltage = 0.0")
    op.alter_column('bb_resistance_path_data', 'raw_voltage', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bb_resistance_path_data', 'raw_voltage')
    # ### end Alembic commands ###
