"""changing path name to path id

Revision ID: d3137acd9da9
Revises: d048a04b0249
Create Date: 2025-04-23 11:26:18.608897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3137acd9da9'
down_revision: Union[str, None] = 'd048a04b0249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bb_resistance_path', sa.Column('path_id', sa.Integer(), nullable=False))
    op.drop_column('bb_resistance_path', 'path_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bb_resistance_path', sa.Column('path_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('bb_resistance_path', 'path_id')
    # ### end Alembic commands ###
